apiVersion: v1
kind: Pod
metadata:
  name: py-app-pod
spec:
  containers:
  - name: py-app-container
    image: phenomsg/py_app:latest
    imagePullPolicy: Always
    command: ["bash", "-c", "while true; do sleep 3600; done"]
